#include "viewports.h"

SDL_FRect game_viewports[GAME_VIEWPORT_COUNT];

void setup_viewports()
{
    GAME_VIEWPORT = (SDL_FRect){.x = 0, .y = BAR_HEIGHT, .w = MIN_BUTTON.x - BUTTON_BORDER, .h = BASE_SCREEN_HEIGHT};
    RIGHT_BAR_VIEWPORT = (SDL_FRect
    ){.x = MIN_BUTTON.x - BUTTON_BORDER,
      .y = BAR_HEIGHT,
      .w = SCREEN_WIDTH - MIN_BUTTON.x + BUTTON_BORDER,
      .h = BASE_SCREEN_HEIGHT};

    DRAW_BUTTON_VIEWPORT.w = 141;
    DRAW_BUTTON_VIEWPORT.h = 47;
    DRAW_BUTTON_VIEWPORT.x = RIGHT_BAR_VIEWPORT.x + (RIGHT_BAR_VIEWPORT.w - DRAW_BUTTON_VIEWPORT.w) / 2;
    DRAW_BUTTON_VIEWPORT.y = RIGHT_BAR_VIEWPORT.y + (RIGHT_BAR_VIEWPORT.h - DRAW_BUTTON_VIEWPORT.h) / 2;

    HAND_VIEWPORT.w = 0.5 * GAME_VIEWPORT.w;
    HAND_VIEWPORT.h = 0.15 * GAME_VIEWPORT.h;
    HAND_VIEWPORT.x = (GAME_VIEWPORT.w - HAND_VIEWPORT.w) / 2;
    HAND_VIEWPORT.y = BAR_HEIGHT + GAME_VIEWPORT.h - HAND_VIEWPORT.h;
}
